server:
  port: 8090

spring:
  application:
    name: service-layer
#  datasource:
#    url: jdbc:h2:mem:service-layer-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      leak-detection-threshold: 2000
#      pool-name: HikariCP-Pool-Service-Layer
#      driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show_sql: true
#    open-in-view: false
#    properties:
#      hibernate.hibernate.dialect : org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true